"""Русские и таджикские названия команд.

Оба источника отдают названия латиницей и в своём написании: «Bayern München»,
«Internazionale», «Spain». Для сайта с русской и таджикской аудиторией это
нечитаемо, а транслитерация тут не работает: русские названия клубов
договорные, а не фонетические. «Bayern» — это Бавария, «Inter» — Интер,
«Spain» — Испания; побуквенный перевод дал бы «Байерн», «Интернационале»,
«Спаин». Поэтому здесь ручной справочник.

Таджикское написание выводится из русского автоматически (to_tajik): в
таджикском алфавите нет ц, щ, ы и ь, остальные буквы те же. Для слов, где
таджикский язык использует собственное название, а не заимствование, есть
отдельная таблица TAJIK.

Клубы Лигаи Олӣ сюда не входят — у них свой выверенный справочник
в app/teams_tj.py, и он имеет приоритет.
"""
import re

from app.sync.fdorg import normalize

# Буквы, которых нет в таджикском алфавите. Для заимствованных названий
# («Манчестер Юнайтед») этого достаточно: ғ, қ, ӯ, ҳ, ҷ, ӣ ставятся в исконных
# словах, а не в переданных с другого языка.
_TJ_MAP = str.maketrans({"ы": "и", "Ы": "И",
                         "ц": "с", "Ц": "С",
                         "щ": "ш", "Щ": "Ш",
                         "ь": "", "Ь": ""})


def to_tajik(ru: str) -> str:
    """Русское написание -> таджикское.

    Аббревиатуры не трогаем: «ЦСКА» по правилу ц->с превратился бы в «ССКА»,
    а читается он одинаково на обоих языках. Признак — слово целиком заглавными.
    """
    if not ru:
        return ""
    return _WORD.sub(lambda m: m.group(0) if _is_abbr(m.group(0))
                     else m.group(0).translate(_TJ_MAP), ru)


_WORD = re.compile(r"[^\W\d_]+", re.UNICODE)


def _is_abbr(w: str) -> bool:
    return len(w) > 1 and w.isupper()


# Названия, где таджикский не заимствует русское слово, а имеет своё.
# Ключ — русское написание из TEAMS.
# Сверено с Wikidata: для каждой страны брались сразу русская и таджикская
# подписи, и таджикская принималась только если русская совпала с нашей —
# иначе легко утащить подпись не той статьи.
#
# Шесть стран сознательно не внесены, хотя подписи у них есть: Австрия (Утриш),
# Канада (Конодо), Украина (Укройн), Колумбия (Кулумбия), Уругвай (Уругуай),
# Эквадор (Экуадор). Это персидские формы, в таджикской прессе так не пишут —
# для них достаточно обычного преобразования.
TAJIK = {
    "Азербайджан": "Озарбойҷон",
    "Алжир": "Алҷазоир",
    "Армения": "Арманистон",
    "Венгрия": "Маҷористон",
    "Гана": "Ғано",
    "Германия": "Олмон",
    "Греция": "Юнон",
    "Грузия": "Гурҷистон",
    "Египет": "Миср",
    "Израиль": "Исроил",
    "Ирак": "Ироқ",
    "Иран": "Эрон",
    "Испания": "Испониё",
    "Италия": "Итолиё",
    "Казахстан": "Қазоқистон",
    "Катар": "Қатар",
    "Марокко": "Марокаш",
    "Нидерланды": "Ҳоланд",
    "Новая Зеландия": "Зеландияи Нав",
    "Польша": "Лаҳистон",
    "Турция": "Туркия",
    "Узбекистан": "Ӯзбекистон",
    "Франция": "Фаронса",
    "Швейцария": "Суис",
    "Швеция": "Суэд",
    "Япония": "Ҷопон",
    # Wikidata не подтвердила — вписано вручную, стоит проверить носителю.
    "Саудовская Аравия": "Арабистони Саудӣ",
    # Сборные (матчи сборной Таджикистана)
    "Таджикистан": "Тоҷикистон",
    "Афганистан": "Афғонистон",
    "Китай": "Хитой",
    "Кыргызстан": "Қирғизистон",
    "Ливан": "Лубнон",
    "Монголия": "Муғулистон",
    "Мьянма": "Мянма",
    "Палестина": "Фаластин",
    "Филиппины": "Филиппин",
    "Россия": "Русия",
    "Сирия": "Сурия",
    "Восточный Тимор": "Тимори Шарқӣ",
    "Туркменистан": "Туркманистон",
    "ОАЭ": "АМИ",
}

# Нормализованное латинское имя -> русское название.
# Ключи получены через fdorg.normalize(), поэтому «Man City» и «Manchester City»
# сходятся в одну запись.
TEAMS = {
    # ---------------------------------------------------------------- Англия
    "arsenal": "Арсенал",
    "aston villa": "Астон Вилла",
    "bournemouth": "Борнмут",
    "brentford": "Брентфорд",
    "brighton": "Брайтон",
    "brighton hove": "Брайтон",
    "chelsea": "Челси",
    "coventry": "Ковентри",
    "coventry city": "Ковентри",
    "crystal palace": "Кристал Пэлас",
    "everton": "Эвертон",
    "fulham": "Фулхэм",
    "hull city": "Халл Сити",
    "ipswich": "Ипсвич",
    "ipswich town": "Ипсвич",
    "leeds": "Лидс",
    "leeds united": "Лидс",
    "liverpool": "Ливерпуль",
    "manchester city": "Манчестер Сити",
    "manchester united": "Манчестер Юнайтед",
    "newcastle": "Ньюкасл",
    "nottingham": "Ноттингем Форест",
    "nottingham forest": "Ноттингем Форест",
    "sunderland": "Сандерленд",
    "tottenham": "Тоттенхэм",

    # ---------------------------------------------------------------- Испания
    "alaves": "Алавес",
    "athletic": "Атлетик",
    "athletic club": "Атлетик",
    "atletico madrid": "Атлетико",
    "barcelona": "Барселона",
    "celta": "Сельта",
    "celta vigo": "Сельта",
    "deportivo": "Депортиво",
    "deportivo la coruna": "Депортиво",
    "elche": "Эльче",
    "espanyol": "Эспаньол",
    "getafe": "Хетафе",
    "levante": "Леванте",
    "malaga": "Малага",
    "osasuna": "Осасуна",
    "racing santander": "Расинг Сантандер",
    "santander": "Расинг Сантандер",
    "rayo vallecano": "Райо Вальекано",
    "real betis": "Бетис",
    "real madrid": "Реал Мадрид",
    "real sociedad": "Реал Сосьедад",
    "sevilla": "Севилья",
    "valencia": "Валенсия",
    "villarreal": "Вильярреал",

    # ---------------------------------------------------------------- Италия
    "milan": "Милан",
    "roma": "Рома",
    "atalanta": "Аталанта",
    "bologna": "Болонья",
    "cagliari": "Кальяри",
    "como": "Комо",
    "como 1907": "Комо",
    "fiorentina": "Фиорентина",
    "frosinone": "Фрозиноне",
    "genoa": "Дженоа",
    "internazionale": "Интер",
    "juventus": "Ювентус",
    "lazio": "Лацио",
    "lecce": "Лечче",
    "monza": "Монца",
    "napoli": "Наполи",
    "parma": "Парма",
    "sassuolo": "Сассуоло",
    "torino": "Торино",
    "udinese": "Удинезе",
    "venezia": "Венеция",

    # ---------------------------------------------------------------- Германия
    "1 koln": "Кёльн",
    "1899 hoffenheim": "Хоффенхайм",
    "hoffenheim": "Хоффенхайм",
    "bayer leverkusen": "Байер",
    "leverkusen": "Байер",
    "bayern": "Бавария",
    "bayern munchen": "Бавария",
    "borussia dortmund": "Боруссия Дортмунд",
    "dortmund": "Боруссия Дортмунд",
    "borussia monchengladbach": "Боруссия Мёнхенгладбах",
    "bremen": "Вердер",
    "werder bremen": "Вердер",
    "eintracht frankfurt": "Айнтрахт",
    "frankfurt": "Айнтрахт",
    "augsburg": "Аугсбург",
    "schalke": "Шальке",
    "schalke 04": "Шальке",
    "fsv mainz 05": "Майнц",
    "mainz": "Майнц",
    "hamburger": "Гамбург",
    "rb leipzig": "РБ Лейпциг",
    "freiburg": "Фрайбург",
    "paderborn": "Падерборн",
    "paderborn 07": "Падерборн",
    "elversberg": "Эльферсберг",
    "union berlin": "Унион Берлин",
    "stuttgart": "Штутгарт",

    # ---------------------------------------------------------------- Франция
    "angers": "Анже",
    "angers sco": "Анже",
    "auxerre": "Осер",
    "brest": "Брест",
    "stade brestois 29": "Брест",
    "estac troyes": "Труа",
    "troyes": "Труа",
    "le havre": "Гавр",
    "le mans": "Ле-Ман",
    "lens": "Ланс",
    "lille": "Лилль",
    "lorient": "Лорьян",
    "lyon": "Лион",
    "olympique lyon": "Лион",
    "marseille": "Марсель",
    "monaco": "Монако",
    "nice": "Ницца",
    "paris": "Пари ФК",
    "paris saint germain": "ПСЖ",
    "rennes": "Ренн",
    "strasbourg": "Страсбур",
    "toulouse": "Тулуза",

    # ---------------------------------------------------------------- прочая Европа
    "aek athens": "АЕК",
    "pae aek": "АЕК",
    "bodø glimt": "Буде-Глимт",
    "club brugge": "Брюгге",
    "club brugge kv": "Брюгге",
    "fenerbahce": "Фенербахче",
    "galatasaray": "Галатасарай",
    "feyenoord": "Фейеноорд",
    "psv": "ПСВ",
    "lask": "ЛАСК",
    "lask linz": "ЛАСК",
    "porto": "Порту",
    "sporting cp": "Спортинг",
    "sabah": "Сабах",
    "shaktar": "Шахтёр",
    "sl bratislava": "Слован Братислава",
    "slavia praha": "Славия Прага",
    "viking": "Викинг",

    # ---------------------------------------------------------------- Россия
    "akhmat": "Ахмат",
    "akron": "Акрон",
    "baltika": "Балтика",
    "cska moscow": "ЦСКА",
    "dinamo makhachkala": "Динамо Махачкала",
    "dynamo": "Динамо",
    "fakel": "Факел",
    "krasnodar": "Краснодар",
    "krylia sovetov": "Крылья Советов",
    "lokomotiv": "Локомотив",
    "orenburg": "Оренбург",
    "rodina moskva": "Родина",
    "rostov": "Ростов",
    "rubin": "Рубин",
    "spartak moscow": "Спартак",
    "zenit": "Зенит",

    # ---------------------------------------------------------------- Саудовская Аравия
    "abha": "Абха",
    "al ahli jeddah": "Аль-Ахли",
    "al ettifaq": "Аль-Иттифак",
    "al faisaly": "Аль-Файсали",
    "al fateh": "Аль-Фатех",
    "al fayha": "Аль-Файха",
    "al hazm": "Аль-Хазм",
    "al hilal saudi": "Аль-Хиляль",
    "al ittihad": "Аль-Иттихад",
    "al khaleej saihat": "Аль-Халидж",
    "al nassr": "Аль-Наср",
    "al qadisiyah": "Аль-Кадисия",
    "al riyadh": "Аль-Рияд",
    "al shabab": "Аль-Шабаб",
    "al taawon": "Аль-Таавун",
    "neom": "НЕОМ",

    # ---------------------------------------------------------------- MLS
    "atlanta united": "Атланта Юнайтед",
    "austin": "Остин",
    "charlotte": "Шарлотт",
    "chicago fire": "Чикаго Файр",
    "cincinnati": "Цинциннати",
    "colorado rapids": "Колорадо Рэпидз",
    "columbus crew": "Коламбус Крю",
    "dallas": "Даллас",
    "dc united": "Ди Си Юнайтед",
    "houston dynamo": "Хьюстон Динамо",
    "inter miami": "Интер Майами",
    "los angeles": "Лос-Анджелес ФК",
    "los angeles galaxy": "Лос-Анджелес Гэлакси",
    "minnesota united": "Миннесота Юнайтед",
    "montreal": "Монреаль",
    "nashville": "Нэшвилл",
    "new england revolution": "Нью-Инглэнд Революшн",
    "new york city": "Нью-Йорк Сити",
    "new york red bulls": "Нью-Йорк Ред Буллз",
    "orlando city": "Орландо Сити",
    "philadelphia union": "Филадельфия Юнион",
    "portland timbers": "Портленд Тимберс",
    "real salt lake": "Реал Солт-Лейк",
    "san diego": "Сан-Диего",
    "san jose earthquakes": "Сан-Хосе Эртквейкс",
    "seattle sounders": "Сиэтл Саундерс",
    "sporting kansas city": "Спортинг Канзас-Сити",
    "st louis city": "Сент-Луис Сити",
    "toronto": "Торонто",
    "vancouver whitecaps": "Ванкувер Уайткэпс",

    # ---------------------------------------------------------------- сборные
    "albania": "Албания",
    "algeria": "Алжир",
    "argentina": "Аргентина",
    "armenia": "Армения",
    "australia": "Австралия",
    "austria": "Австрия",
    "azerbaijan": "Азербайджан",
    "belarus": "Беларусь",
    "belgium": "Бельгия",
    "bosnia and herzegovina": "Босния и Герцеговина",
    "bosnia h": "Босния и Герцеговина",
    "brazil": "Бразилия",
    "bulgaria": "Болгария",
    "canada": "Канада",
    "cape verde": "Кабо-Верде",
    "colombia": "Колумбия",
    "congo dr": "ДР Конго",
    "croatia": "Хорватия",
    "curacao": "Кюрасао",
    "cyprus": "Кипр",
    "czechia": "Чехия",
    "denmark": "Дания",
    "ecuador": "Эквадор",
    "egypt": "Египет",
    "england": "Англия",
    "estonia": "Эстония",
    "faroe islands": "Фарерские острова",
    "finland": "Финляндия",
    "france": "Франция",
    "fyr macedonia": "Северная Македония",
    "georgia": "Грузия",
    "germany": "Германия",
    "ghana": "Гана",
    "gibraltar": "Гибралтар",
    "greece": "Греция",
    "haiti": "Гаити",
    "hungary": "Венгрия",
    "iceland": "Исландия",
    "iran": "Иран",
    "iraq": "Ирак",
    "israel": "Израиль",
    "italy": "Италия",
    "ivory coast": "Кот-д’Ивуар",
    "japan": "Япония",
    "jordan": "Иордания",
    "kazakhstan": "Казахстан",
    "korea republic": "Южная Корея",
    "kosovo": "Косово",
    "latvia": "Латвия",
    "liechtenstein": "Лихтенштейн",
    "luxembourg": "Люксембург",
    "malta": "Мальта",
    "mexico": "Мексика",
    "moldova": "Молдова",
    "montenegro": "Черногория",
    "morocco": "Марокко",
    "netherlands": "Нидерланды",
    "new zealand": "Новая Зеландия",
    "northern ireland": "Северная Ирландия",
    "norway": "Норвегия",
    "panama": "Панама",
    "paraguay": "Парагвай",
    "poland": "Польша",
    "portugal": "Португалия",
    "qatar": "Катар",
    "rep of ireland": "Ирландия",
    "romania": "Румыния",
    "san marino": "Сан-Марино",
    "saudi arabia": "Саудовская Аравия",
    "scotland": "Шотландия",
    "senegal": "Сенегал",
    "serbia": "Сербия",
    "slovakia": "Словакия",
    "slovenia": "Словения",
    "south africa": "ЮАР",
    "spain": "Испания",
    "sweden": "Швеция",
    "switzerland": "Швейцария",
    "tunisia": "Тунис",
    "turkey": "Турция",
    "turkiye": "Турция",
    "ukraine": "Украина",
    "uruguay": "Уругвай",
    "usa": "США",
    "uzbekistan": "Узбекистан",
    "wales": "Уэльс",
    # ---------------------------------------------------------------- Сборные (матчи сборной Таджикистана)
    "tajikistan": "Таджикистан",
    "afghanistan": "Афганистан",
    "china": "Китай",
    "hong kong": "Гонконг",
    "kuwait": "Кувейт",
    "kyrgyzstan": "Кыргызстан",
    "lebanon": "Ливан",
    "malaysia": "Малайзия",
    "maldives": "Мальдивы",
    "mongolia": "Монголия",
    "myanmar": "Мьянма",
    "nepal": "Непал",
    "oman": "Оман",
    "palestine": "Палестина",
    "philippines": "Филиппины",
    "russia": "Россия",
    "singapore": "Сингапур",
    "syria": "Сирия",
    "timor leste": "Восточный Тимор",
    "turkmenistan": "Туркменистан",
    "uganda": "Уганда",
    "united arab emirates": "ОАЭ",
}


# Каноническое английское написание. Источники шлют то «Man City», то
# «Manchester City», то «Bosnia-H.» — на английском интерфейсе нужна одна
# форма, а не та, что пришла в конкретном ответе.
ENGLISH = {
    "1 koln": "FC Köln",
    "1899 hoffenheim": "Hoffenheim",
    "abha": "Abha",
    "aek athens": "AEK Athens FC",
    "akhmat": "Akhmat",
    "akron": "Akron",
    "al ahli jeddah": "Al-Ahli Jeddah",
    "al ettifaq": "Al-Ettifaq",
    "al faisaly": "Al-Faisaly",
    "al fateh": "Al-Fateh",
    "al fayha": "Al-Fayha",
    "al hazm": "Al-Hazm",
    "al hilal saudi": "Al-Hilal",
    "al ittihad": "Al-Ittihad",
    "al khaleej saihat": "Al Khaleej Saihat",
    "al nassr": "Al-Nassr",
    "al qadisiyah": "Al-Qadisiyah",
    "al riyadh": "Al Riyadh",
    "al shabab": "Al Shabab",
    "al taawon": "Al Taawon",
    "alaves": "Alaves",
    "albania": "Albania",
    "algeria": "Algeria",
    "angers": "Angers",
    "angers sco": "Angers",
    "argentina": "Argentina",
    "armenia": "Armenia",
    "arsenal": "Arsenal",
    "aston villa": "Aston Villa",
    "atalanta": "Atalanta",
    "athletic": "Athletic Club",
    "athletic club": "Athletic Club",
    "atlanta united": "Atlanta United FC",
    "atletico madrid": "Atletico Madrid",
    "augsburg": "FC Augsburg",
    "austin": "Austin",
    "australia": "Australia",
    "austria": "Austria",
    "auxerre": "Auxerre",
    "azerbaijan": "Azerbaijan",
    "baltika": "Baltika",
    "barcelona": "Barcelona",
    "bayer leverkusen": "Bayer Leverkusen",
    "bayern": "Bayern Munich",
    "bayern munchen": "Bayern Munich",
    "belarus": "Belarus",
    "belgium": "Belgium",
    "bodø glimt": "Bodø/Glimt",
    "bologna": "Bologna",
    "borussia dortmund": "Borussia Dortmund",
    "borussia monchengladbach": "Borussia Mönchengladbach",
    "bosnia and herzegovina": "Bosnia & Herzegovina",
    "bosnia h": "Bosnia & Herzegovina",
    "bournemouth": "Bournemouth",
    "brazil": "Brazil",
    "bremen": "Bremen",
    "brentford": "Brentford",
    "brest": "Brest",
    "brighton": "Brighton & Hove Albion",
    "brighton hove": "Brighton & Hove Albion",
    "bulgaria": "Bulgaria",
    "cagliari": "Cagliari",
    "canada": "Canada",
    "cape verde": "Cape Verde",
    "celta": "Celta Vigo",
    "celta vigo": "Celta Vigo",
    "charlotte": "Charlotte",
    "chelsea": "Chelsea",
    "chicago fire": "Chicago Fire",
    "cincinnati": "FC Cincinnati",
    "club brugge": "Club Brugge",
    "club brugge kv": "Club Brugge",
    "colombia": "Colombia",
    "colorado rapids": "Colorado Rapids",
    "columbus crew": "Columbus Crew",
    "como": "Como",
    "como 1907": "Como",
    "congo dr": "DR Congo",
    "coventry": "Coventry",
    "coventry city": "Coventry City",
    "croatia": "Croatia",
    "crystal palace": "Crystal Palace",
    "cska moscow": "CSKA Moscow",
    "curacao": "Curaçao",
    "cyprus": "Cyprus",
    "czechia": "Czechia",
    "dallas": "FC Dallas",
    "dc united": "DC United",
    "denmark": "Denmark",
    "deportivo": "Deportivo La Coruña",
    "deportivo la coruna": "Deportivo La Coruna",
    "dinamo makhachkala": "Dinamo Makhachkala",
    "dortmund": "Dortmund",
    "dynamo": "Dynamo Moscow",
    "ecuador": "Ecuador",
    "egypt": "Egypt",
    "eintracht frankfurt": "Eintracht Frankfurt",
    "elche": "Elche",
    "elversberg": "SV Elversberg",
    "england": "England",
    "espanyol": "Espanyol",
    "estac troyes": "Troyes",
    "estonia": "Estonia",
    "everton": "Everton",
    "fakel": "Fakel",
    "faroe islands": "Faroe Islands",
    "fenerbahce": "Fenerbahçe",
    "feyenoord": "Feyenoord",
    "finland": "Finland",
    "fiorentina": "Fiorentina",
    "france": "France",
    "frankfurt": "Frankfurt",
    "freiburg": "SC Freiburg",
    "frosinone": "Frosinone",
    "fsv mainz 05": "Mainz 05",
    "fulham": "Fulham",
    "fyr macedonia": "North Macedonia",
    "galatasaray": "Galatasaray",
    "genoa": "Genoa",
    "georgia": "Georgia",
    "germany": "Germany",
    "getafe": "Getafe",
    "ghana": "Ghana",
    "gibraltar": "Gibraltar",
    "greece": "Greece",
    "haiti": "Haiti",
    "hamburger": "Hamburger SV",
    "hoffenheim": "Hoffenheim",
    "houston dynamo": "Houston Dynamo",
    "hull city": "Hull City",
    "hungary": "Hungary",
    "iceland": "Iceland",
    "inter miami": "Inter Miami",
    "internazionale": "Inter Milan",
    "ipswich": "Ipswich",
    "ipswich town": "Ipswich Town",
    "iran": "Iran",
    "iraq": "Iraq",
    "israel": "Israel",
    "italy": "Italy",
    "ivory coast": "Côte d'Ivoire",
    "japan": "Japan",
    "jordan": "Jordan",
    "juventus": "Juventus",
    "kazakhstan": "Kazakhstan",
    "korea republic": "South Korea",
    "kosovo": "Kosovo",
    "krasnodar": "FC Krasnodar",
    "krylia sovetov": "Krylia Sovetov",
    "lask": "LASK",
    "lask linz": "LASK",
    "latvia": "Latvia",
    "lazio": "Lazio",
    "le havre": "Le Havre",
    "le mans": "Le Mans",
    "lecce": "Lecce",
    "leeds": "Leeds",
    "leeds united": "Leeds United",
    "lens": "Lens",
    "levante": "Levante",
    "leverkusen": "Leverkusen",
    "liechtenstein": "Liechtenstein",
    "lille": "Lille",
    "liverpool": "Liverpool",
    "lokomotiv": "Lokomotiv",
    "lorient": "Lorient",
    "los angeles": "Los Angeles FC",
    "los angeles galaxy": "Los Angeles Galaxy",
    "luxembourg": "Luxembourg",
    "lyon": "Lyon",
    "mainz": "Mainz",
    "malaga": "Malaga",
    "malta": "Malta",
    "manchester city": "Manchester City",
    "manchester united": "Manchester United",
    "marseille": "Marseille",
    "mexico": "Mexico",
    "milan": "AC Milan",
    "minnesota united": "Minnesota United FC",
    "moldova": "Moldova",
    "monaco": "Monaco",
    "montenegro": "Montenegro",
    "montreal": "CF Montreal",
    "monza": "Monza",
    "morocco": "Morocco",
    "napoli": "Napoli",
    "nashville": "Nashville SC",
    "neom": "NEOM",
    "netherlands": "Netherlands",
    "new england revolution": "New England Revolution",
    "new york city": "New York City FC",
    "new york red bulls": "New York Red Bulls",
    "new zealand": "New Zealand",
    "newcastle": "Newcastle",
    "nice": "Nice",
    "northern ireland": "Northern Ireland",
    "norway": "Norway",
    "nottingham": "Nottingham Forest",
    "nottingham forest": "Nottingham Forest",
    "olympique lyon": "Lyon",
    "orenburg": "FC Orenburg",
    "orlando city": "Orlando City SC",
    "osasuna": "Osasuna",
    "paderborn": "SC Paderborn",
    "paderborn 07": "Paderborn",
    "pae aek": "AEK Athens",
    "panama": "Panama",
    "paraguay": "Paraguay",
    "paris": "Paris FC",
    "paris saint germain": "Paris Saint-Germain",
    "parma": "Parma",
    "philadelphia union": "Philadelphia Union",
    "poland": "Poland",
    "portland timbers": "Portland Timbers",
    "porto": "FC Porto",
    "portugal": "Portugal",
    "psv": "PSV",
    "qatar": "Qatar",
    "racing santander": "Racing Santander",
    "rayo vallecano": "Rayo Vallecano",
    "rb leipzig": "RB Leipzig",
    "real betis": "Real Betis",
    "real madrid": "Real Madrid",
    "real salt lake": "Real Salt Lake",
    "real sociedad": "Real Sociedad",
    "rennes": "Rennes",
    "rep of ireland": "Republic of Ireland",
    "rodina moskva": "Rodina Moskva",
    "roma": "AS Roma",
    "romania": "Romania",
    "rostov": "FC Rostov",
    "rubin": "Rubin",
    "sabah": "Sabah FK",
    "san diego": "San Diego",
    "san jose earthquakes": "San Jose Earthquakes",
    "san marino": "San Marino",
    "santander": "Racing Santander",
    "sassuolo": "Sassuolo",
    "saudi arabia": "Saudi Arabia",
    "schalke": "Schalke",
    "schalke 04": "Schalke 04",
    "scotland": "Scotland",
    "seattle sounders": "Seattle Sounders",
    "senegal": "Senegal",
    "serbia": "Serbia",
    "sevilla": "Sevilla",
    "shaktar": "Shakhtar Donetsk",
    "sl bratislava": "Slovan Bratislava",
    "slavia praha": "Slavia Praha",
    "slovakia": "Slovakia",
    "slovenia": "Slovenia",
    "south africa": "South Africa",
    "spain": "Spain",
    "spartak moscow": "Spartak Moscow",
    "sporting cp": "Sporting CP",
    "sporting kansas city": "Sporting Kansas City",
    "st louis city": "St. Louis City",
    "stade brestois 29": "Brest",
    "strasbourg": "Strasbourg",
    "stuttgart": "VfB Stuttgart",
    "sunderland": "Sunderland",
    "sweden": "Sweden",
    "switzerland": "Switzerland",
    "torino": "Torino",
    "toronto": "Toronto FC",
    "tottenham": "Tottenham",
    "toulouse": "Toulouse",
    "troyes": "Troyes",
    "tunisia": "Tunisia",
    "turkey": "Turkey",
    "turkiye": "Turkey",
    "udinese": "Udinese",
    "ukraine": "Ukraine",
    "union berlin": "Union Berlin",
    "uruguay": "Uruguay",
    "usa": "United States",
    "uzbekistan": "Uzbekistan",
    "valencia": "Valencia",
    "vancouver whitecaps": "Vancouver Whitecaps",
    "venezia": "Venezia",
    "viking": "Viking",
    "villarreal": "Villarreal",
    "wales": "Wales",
    "werder bremen": "Werder Bremen",
    "zenit": "Zenit",
    # ---------------------------------------------------------------- Сборные
    "tajikistan": "Tajikistan",
    "afghanistan": "Afghanistan",
    "china": "China",
    "hong kong": "Hong Kong",
    "kuwait": "Kuwait",
    "kyrgyzstan": "Kyrgyzstan",
    "lebanon": "Lebanon",
    "malaysia": "Malaysia",
    "maldives": "Maldives",
    "mongolia": "Mongolia",
    "myanmar": "Myanmar",
    "nepal": "Nepal",
    "oman": "Oman",
    "palestine": "Palestine",
    "philippines": "Philippines",
    "russia": "Russia",
    "singapore": "Singapore",
    "syria": "Syria",
    "timor leste": "Timor-Leste",
    "turkmenistan": "Turkmenistan",
    "uganda": "Uganda",
    "united arab emirates": "UAE",
}


def team_names(latin: str | None) -> tuple[str, str, str] | None:
    """(русское, таджикское, английское) или None для неизвестной команды."""
    key = normalize(latin or "")
    ru = TEAMS.get(key)
    if not ru:
        return None
    return ru, TAJIK.get(ru) or to_tajik(ru), ENGLISH.get(key) or latin or ru
